# Generated by Django 3.2 on 2022-01-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220117_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line_2',
            new_name='street_address2',
        ),
    ]
