# Generated by Django 3.2 on 2022-01-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220107_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ease_of_care',
            field=models.CharField(blank=True, choices=[('needs_a_bit_of_love', 'NEEDS A BIT OF LOVE'), ('can_be_a_diva', 'CAN BE A DIVA'), ('practically_unkillable', 'PRACTICALLY UNKILLABLE'), ('easy_to_care_for', 'EASY TO CARE FOR')], max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='growth_need',
            field=models.CharField(blank=True, choices=[('takes_its_time', 'TAKES ITS TIME'), ('fast_grower', 'FAST GROWER'), ('lifelong_friend', 'LIFELONG FRIEND')], max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='humidity_need',
            field=models.CharField(blank=True, choices=[('prefers_humidity', 'PREFERS HUMIDITY'), ('prefers_dry air', 'PREFERS DRY AIR'), ('likes_a_little moisture', 'LIKES A LITTLE MOISTURE')], max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='light_need',
            field=models.CharField(blank=True, choices=[('loves_the_shade', 'LOVES THE SHADE'), ('loves_bright_light', 'LOVES BRIGHT LIGHT'), ('loves_a_bit_of_both', 'LOVES A BIT OF BOTH')], max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='seasonal_collection',
            field=models.CharField(blank=True, choices=[('winter', 'WINTER'), ('valentines', 'VALENTINES'), ('summer', 'SUMMER'), ('spring', 'SPRING')], max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('one pair', 'ONE PAIR'), ('various sizes', 'VARIOUS SIZES'), ('20kg', '20KG'), ('one bunch', 'ONE BUNCH'), ('1l', '1L'), ('10kg', '10KG'), ('small', 'SMALL'), ('500ml', '500ml'), ('medium', 'MEDIUM'), ('5kg', '5KG'), ('large', 'LARGE'), ('1x pack', '1X PACK')], max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='temp_need',
            field=models.CharField(blank=True, choices=[('keep_warm', 'KEEP WARM'), ('keep_cool', 'KEEP COOL'), ('keep_at_room_temperature', 'KEEP AT ROOM TEMPERATURE')], max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='water_need',
            field=models.CharField(blank=True, choices=[('light_watering', 'LIGHT WATERING'), ('always_thirsty', 'ALWAYS THIRSTY'), ('water_only_when_dry', 'WATER ONLY WHEN DRY')], max_length=254),
        ),
    ]
